version: '3.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  spring-app:
    image: wallet-msir-jour-groupe3:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis


networks:
  mynetwork:
